# Generated by Django 3.2.9 on 2021-11-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ncm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descricao', models.CharField(max_length=500)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('nacionalFederal', models.FloatField(blank=True, null=True)),
                ('importadosFederal', models.FloatField(blank=True, null=True)),
                ('estadual', models.FloatField(blank=True, null=True)),
                ('municipal', models.FloatField(blank=True, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fim', models.DateField(blank=True, null=True)),
                ('atualizacao', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NCM',
                'verbose_name_plural': 'NCM',
            },
        ),
    ]
